# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0002_auto_20170927_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contact_number',
            new_name='phone',
        ),
    ]
