# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0004_auto_20171002_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to=b'Images/'),
        ),
    ]
