# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0009_auto_20171005_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default=b'/UserImages/default.png', upload_to=b'UserImages/'),
        ),
    ]
