# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0010_auto_20171005_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
